//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPGenerator.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseAccount
    {
        public int ExpenseAccountID { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public string AccountName { get; set; }
        public Nullable<bool> SubAccount { get; set; }
        public string AccountCode { get; set; }
        public string Description { get; set; }
    }
}
