//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPGenerator.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.Guid> InvoiceNo { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> SalesPersonID { get; set; }
        public string Subject { get; set; }
        public Nullable<decimal> ShippingCharges { get; set; }
        public Nullable<decimal> AdjustmentValue { get; set; }
        public string AdjustmentText { get; set; }
    }
}
