//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPGenerator.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTotalMade
    {
        public int PaymentTotalMadeID { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> AmountUsedForPayments { get; set; }
        public Nullable<decimal> AmountRefunded { get; set; }
        public Nullable<decimal> AmountInExcess { get; set; }
    }
}
