//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPGenerator.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordMileage
    {
        public int RecordMileageID { get; set; }
        public Nullable<bool> AssociateEmployees { get; set; }
        public Nullable<int> DefaultMileageAccountID { get; set; }
        public Nullable<int> DefaultUnitID { get; set; }
        public Nullable<decimal> MileageRate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
