//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPGenerator.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetainerInvoice
    {
        public int RetainerInvoiceID { get; set; }
        public Nullable<int> ReferenceNo { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.Guid> RetainerInvoiceNo { get; set; }
        public Nullable<System.DateTime> RetainerInvoiceDate { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<decimal> AdjustmentValue { get; set; }
        public string CustomerNotes { get; set; }
        public string AdjustmentText { get; set; }
        public Nullable<decimal> ShippingCharges { get; set; }
    }
}
