//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPGenerator.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnpaidInvoice
    {
        public int UnpaidInvoiceID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public Nullable<decimal> Payment { get; set; }
    }
}
