//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPGenerator.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorCredit
    {
        public int VendorCreditID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string CreditNoteNo { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> VendorCreditDate { get; set; }
        public Nullable<int> ItemDetailID { get; set; }
        public string AdjustmentText { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> AdjustmentValue { get; set; }
        public Nullable<decimal> ShippingCharges { get; set; }
    }
}
